name: E2E Tests

on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  e2e-run:
    if: contains(github.event.pull_request.labels.*.name, 'e2e-tests')
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    #   matrix:
    #     containers: [1, 2] # Uses 2 parallel instances
    steps:
     - name: Checkout Repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.inputs.branch }}
    # - name: Checkout code
    #   uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install depdendencies
      run: yarn install --pure-lockfile
    - name: Build
        run: yarn build --mode staging
        env:
          VITE_REACT_APP_DEPLOY_VERSION: ${{ github.sha }}
          VITE_REACT_APP_DEPLOY_ENVIRONMENT: ${{ needs.set-environment.outputs.environment }}
          VITE_REACT_APP_ANALYTICS_KEY: ${{ secrets.VITE_REACT_APP_ANALYTICS_KEY }}
          VITE_IPFS_API_KEY: ${{secrets.VITE_IPFS_API_KEY}}
          VITE_ETHERSCAN_API_KEY: ${{secrets.VITE_ETHERSCAN_API_KEY}}
          VITE_POLYGONSCAN_API_KEY: ${{secrets.VITE_POLYGONSCAN_API_KEY}}
          VITE_INFURA_GOERLI_PROJECT_ID: ${{secrets.VITE_INFURA_GOERLI_PROJECT_ID}}
          VITE_INFURA_MAINNET_PROJECT_ID: ${{secrets.VITE_INFURA_MAINNET_PROJECT_ID}}
          VITE_WALLET_CONNECT_PROJECT_ID: ${{secrets.VITE_WALLET_CONNECT_PROJECT_ID}}
          VITE_INFURA_API_KEY: ${{secrets.VITE_INFURA_API_KEY}}
          VITE_ALCHEMY_KEY_POLYGON_MUMBAI: ${{secrets.VITE_ALCHEMY_KEY_POLYGON_MUMBAI}}
          VITE_ALCHEMY_KEY_POLYGON_MAINNET: ${{secrets.VITE_ALCHEMY_KEY_POLYGON_MUMBAI}}
          VITE_ALCHEMY_KEY_MAINNET: ${{secrets.VITE_ALCHEMY_KEY_MAINNET}}
          VITE_ALCHEMY_KEY_GOERLI: ${{secrets.VITE_ALCHEMY_KEY_GOERLI}}
          VITE_COVALENT_API_KEY: ${{secrets.VITE_COVALENT_API_KEY}}
          NODE_OPTIONS: '--max-old-space-size=6656'
    - name: Run E2E Tests
        uses: yarn e2e
        with:
          start: yarn dev
          wait-on: 'http://localhost:3000'
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_RECORD_KEY: '0c4de406-82ab-48c2-94b1-6267578d2f33' # key of testing project
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

