name: WebApp Push
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/web-app/**'

env:
  working-directory: packages/web-app

jobs:
  test:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-16
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build ui-components
        run: |
          cd ../ui-components
          yarn install --pure-lockfile
          yarn build
          yarn link
      - name: Install depdendencies
        run: yarn install --pure-lockfile
      - name: Link ui-components
        run: yarn link @aragon/ui-components
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
        env:
          VITE_REACT_APP_DEPLOY_VERSION: ${{ github.sha }}
          VITE_REACT_APP_DEPLOY_ENVIRONMENT: ${{ needs.set-environment.outputs.environment }}
          VITE_REACT_APP_ANALYTICS_KEY: ${{ secrets.VITE_REACT_APP_ANALYTICS_KEY }}
          VITE_REACT_APP_RPC: "mainnet.eth.aragon.network"
          # TODO
          # Remove when the SDK no longer needs the addresses of the contract
          VITE_REACT_APP_SDK_DAO_FACTORY_ADDRESS: "0xa0b2B729DE73cd22406d3D5A31816985c04A7cdD"
          # "address1,address2,address3,...,addressN"
          VITE_REACT_APP_SDK_WEB3_PROVIDERS: "https://eth-rinkeby.alchemyapi.io/v2/bgIqe2NxazpzsjfmVmhj3aS3j_HZ9mpr"
          NODE_OPTIONS: '--max-old-space-size=6656'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./packages/web-app/
          args: >
            -Dsonar.organization=aragon
            -Dsonar.projectKey=aragon_zaragoza
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.sources=src/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
