name: WebApp Test
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/web-app/**'
    branches-ignore:  ## Ignore develop and main branches to avoid an unneeded 2nd build.
      - 'develop'
      - 'main'

env:
  working-directory: packages/web-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-16
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Build ui-components
        run: |
          cd ../ui-components
          yarn install --pure-lockfile
          yarn build
          yarn link
      - name: Install depdendencies
        run: yarn install --pure-lockfile
      - name: Link ui-components
        run: yarn link @aragon/ui-components
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
        env:
          VITE_REACT_APP_DEPLOY_VERSION: ${{ github.sha }}
          VITE_REACT_APP_DEPLOY_ENVIRONMENT: ${{ needs.set-environment.outputs.environment }}
          VITE_REACT_APP_ANALYTICS_KEY: ${{ secrets.VITE_REACT_APP_ANALYTICS_KEY }}
          VITE_IPFS_API_KEY: ${{secrets.VITE_IPFS_API_KEY}}
          VITE_ETHERSCAN_API_KEY: ${{secrets.VITE_ETHERSCAN_API_KEY}}
          NODE_OPTIONS: '--max-old-space-size=6656'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./packages/web-app/
          args: >
            -Dsonar.organization=aragon
            -Dsonar.projectKey=aragon_zaragoza
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.sources=src/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
